apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
